## Gradle Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Minecraft Properties
minecraft_version=26.2
minecraft_version_range=[26.2,)
neo_version=26.2.0.1-beta
neo_version_range=[26.2.0.1-beta,)
loader_version_range=[4,)

## Mod Properties
mod_id=placeholder_api
mod_name=Placeholder API Neoforge
mod_license=LGPLv3
mod_version=3.1.0-beta.1+26.2
mod_group_id=eu.pb4.placeholders
mod_authors=Patbox
mod_description=Unofficial placeholders api port. Simple api for mods allowing for user friendly formatting and universal placeholders!
